management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, health
logging:
  level:
    root: INFO
    com.juemlis.processor.ValidCredentials: INFO